-- UNA TESSERA NON PUO ESSERE CREATA SE UNA PERSONA NON HA COMPIUTO 21 ANNI
DROP TRIGGER CONTROLLO_ETA;
CREATE OR REPLACE TRIGGER CONTROLLO_ETA
BEFORE INSERT ON PERSONA
FOR EACH ROW
DECLARE
MINORE EXCEPTION;
BEGIN
IF (FLOOR((SYSDATE - :NEW.DATA_DI_NASCITA) / 365)<='21') THEN 
RAISE MINORE;
END IF;
EXCEPTION
WHEN MINORE THEN
RAISE_APPLICATION_ERROR(-20007,'L UTENTE NON PUO ESSERE INSERITO POICHE NON HA RAGGIUNTO LA MAGGIORE ETA');
END;
/