-- Non ci può essere più di un approvvigionamento al giorno. 
CREATE OR REPLACE TRIGGER CAPP
BEFORE INSERT ON APPROVVIGIONAMENTO
FOR EACH ROW
DECLARE
N_APP NUMBER;
ERROR_NOAPP EXCEPTION;
BEGIN
SELECT COUNT(*) INTO N_APP
FROM APPROVVIGIONAMENTO
WHERE DATA_APPROVVIGIONAMENTO= :NEW.DATA_APPROVVIGIONAMENTO;
IF(N_APP>=1) THEN 
RAISE ERROR_NOAPP;
END IF;
EXCEPTION
WHEN ERROR_NOAPP THEN
RAISE_APPLICATION_ERROR(-20009,'NON CI PUO ESSERE PIU DI UN APPROVVIGIONAMENTO AL GIORNO ');
END;
/
