-- Controllare che lo scontrino non sia stato emesso prima della data_inizio della tessera.
-- Controllare che lo scontrino non sia stato emesso dopo la scadenza di una tessera.

CREATE OR REPLACE TRIGGER CONTROLLO_SCONTRINO
BEFORE INSERT ON SCONTRINO
FOR EACH ROW
DECLARE
D_O DATE;
DI DATE;
DF DATE;
ERROR_SCONTRINO_DI EXCEPTION;
ERROR_SCONTRINO_DF EXCEPTION;
BEGIN 
SELECT DATA_INIZIO, DATA_FINE INTO DI, DF
FROM TESSERA
WHERE NUM_TESSERA=:NEW.NUM_TESSERA; 
D_O:=:NEW.DATA_ORA;
IF (D_O<DI OR D_O>DF) then
RAISE ERROR_SCONTRINO_DI;
END IF;
EXCEPTION
WHEN ERROR_SCONTRINO_DI THEN
RAISE_APPLICATION_ERROR(-20003,'ACQUISTO FALLITO, CONTROLLARE LA DATA INIZIO E LA DATA FINE DELLA TESSERA');
END;
/

