/*Questa procedura inserisce approvvigionamento del prodotto piu venduto (in costituito e approvvigionamento) e fa un controllo se questi prodotti inseriti sono presenti in magazzino*/
CREATE OR REPLACE PROCEDURE SCORTE(DATA_APP DATE,DIRETTORE VARCHAR,QUANTITA NUMBER)IS
-- CONTO I NUMERI LOTTI CHE CONTENGONO IL PRODOTTO PIU VENDUTO(CALCOLATI DA UNA FUNCTION).
CURSOR C1 IS SELECT NUM_LOTTO,QUANTITA_LOTTO
	FROM LOTTO L
	WHERE COD_BARRE=BESTP;

EMP_REC C1%ROWTYPE;
Q_VENDUTA NUMBER;
COD_PROD VARCHAR(20);
QUANT_PROD NUMBER;
TOTALE_AGG INTEGER;
MAG_VUOTO EXCEPTION;
TEMP_C1 NUMBER;
NQT NUMBER;
NMAG NUMBER;
PREZZO_FORN NUMBER;
CF_FORN VARCHAR(16);
PREZZO_LOTTO NUMBER;

BEGIN 

-- PREZZO PIU BASSO,DAI FORNITORI, DEL PRODOTTO INSERITO
SELECT F.CF_FORNITORE, PREZZO_FORNITORE INTO CF_FORN,PREZZO_FORN
FROM FORNITORE F JOIN VENDUTO V ON (F.CF_FORNITORE=V.CF_FORNITORE)
WHERE COD_BARRE=COD_PROD AND (PREZZO_FORNITORE) =ANY (SELECT MIN(PREZZO_FORNITORE) 
														FROM VENDUTO 
														WHERE COD_BARRE=COD_PROD);
														

-- MAGAZZINO ASSOCIATO A QUEL DIRETTORE										
SELECT NUM_MAG INTO NMAG
FROM SOCIAL_CLUB S JOIN MAGAZZINO M ON S.LOCALITA=M.LOCALITA
WHERE CF_DIRETTORE=DIRETTORE;


--Somma della quantita del prodotto che mi serve nei vari lotti del magazzino 
QUANT_PROD:= DISPONIB(COD_PROD,DATA_APP);

--Ora devo controllare se la somma dei prodotti in magazzino e' uguale, minore o maggiore di quella che mi serve
TOTALE_AGG:= QUANT_PROD - QUANTITA;

PREZZO_LOTTO:= PREZZO_FORN*100;
--1.Se e' maggiore faccio gli insert nel costituito e nell approvvigionamento con il codice dei lotti in magazzino che contengono il prodotto

IF (TOTALE_AGG>30)THEN
-- INSERISCo APP 
	INSERT INTO APPROVVIGIONAMENTO VALUES (DATA_APP,DIRETTORE);
	OPEN C1;
	LOOP
	FETCH C1 INTO EMP_REC;
	EXIT WHEN C1%NOTFOUND AND (NQT>=QUANTITA);
		NQT:= NQT+EMP_REC.QUANTITA_LOTTO;
		IF(NQT<QUANTITA) THEN
		--INSERISCO UN LOTTO NELL'APPROVVIGIONAMENTO
			INSERT INTO COSTITUITO_L VALUES (EMP_REC.QUANTITA_LOTTO,DIRETTORE,DATA_APP,EMP_REC.NUM_LOTTO);
-- SE E UGUALE ALLA QUANTITA RICHIESTA INSERISCo E POI ESCo DAL CURSORE
		ELSE 
			INSERT INTO COSTITUITO_L VALUES (EMP_REC.QUANTITA_LOTTO,DIRETTORE,DATA_APP,EMP_REC.NUM_LOTTO);
		END IF;
	END LOOP;
	CLOSE C1;
END IF;


--2.Se e' uguale mando una notifica che ora il magazzino e' vuoto e inserisco una fornitura e un lotto con la quantita piu venduta
IF (TOTALE_AGG = 0) THEN
		INSERT INTO APPROVVIGIONAMENTO VALUES (DATA_APP,DIRETTORE);
	OPEN C1;
	LOOP
	FETCH C1 INTO EMP_REC;
		INSERT INTO COSTITUITO_L VALUES (EMP_REC.QUANTITA_LOTTO,DIRETTORE,DATA_APP,EMP_REC.NUM_LOTTO);
	END LOOP;
	CLOSE C1;
		INSERT INTO FORNITURA(COD_FORNITURA,DATA_FOR,CF_FORNITORE,NUM_MAG,CF_DIRETTORE) VALUES
		(NUOVI_COD_FORN.NEXTVAL,SYSDATE,CF_FORN,NMAG,DIRETTORE);
		INSERT INTO LOTTO(NUM_LOTTO,QUANTITA_LOTTO,PREZZO_LOTTO, COD_BARRE, COD_FORNITURA) VALUES
		(NUOVI_NUM_LOTTO.NEXTVAL,100,PREZZO_LOTTO,COD_PROD,NUOVI_COD_FORN.NEXTVAL);
	RAISE MAG_VUOTO;
END IF;

--3.Se e' minore mi porto nel social club quella che ho nel magazzino e in piu inserisco una fornitura e un lotto
IF(TOTALE_AGG < 0) THEN 
INSERT INTO APPROVVIGIONAMENTO VALUES (DATA_APP,DIRETTORE);
	OPEN C1;
	LOOP
	FETCH C1 INTO EMP_REC;
	INSERT INTO COSTITUITO_L VALUES (EMP_REC.QUANTITA_LOTTO,DIRETTORE,DATA_APP,EMP_REC.NUM_LOTTO);
	FETCH C1 INTO EMP_REC;
	END LOOP;
	CLOSE C1;
	INSERT INTO FORNITURA(COD_FORNITURA,DATA_FOR,CF_FORNITORE,NUM_MAG,CF_DIRETTORE) VALUES
	(NUOVI_COD_FORN.NEXTVAL,SYSDATE,CF_FORN,NMAG,DIRETTORE);
	INSERT INTO LOTTO(NUM_LOTTO,QUANTITA_LOTTO,PREZZO_LOTTO, COD_BARRE, COD_FORNITURA) VALUES
	(NUOVI_NUM_LOTTO.NEXTVAL,100,PREZZO_LOTTO,COD_PROD,NUOVI_COD_FORN.NEXTVAL);
	RAISE MAG_VUOTO;
END IF;

EXCEPTION 
WHEN MAG_VUOTO THEN 
dbms_output.put_line('APPROVVIGIONAMENTI INVIATI. MA LE SCORTE IN MAGAZZINO SONO FINITE COSI E STATA INVIATA AUTIMATICAMENTE UNA FORNITURA DI 100 PEZZI');
END SCORTE;
/

