DROP TABLE VENDUTO;
DROP TABLE CONTIENE_R;
DROP TABLE REPARTO;
DROP TABLE COSTITUITO_L;
DROP TABLE APPROVVIGIONAMENTO;
DROP TABLE LOTTO;
DROP TABLE FORNITURA;
DROP TABLE MAGAZZINO;
DROP TABLE CONTIENE;
DROP TABLE PRODOTTO;
DROP TABLE TIPO_PRODOTTO;
DROP TABLE SCONTRINO;
DROP TABLE TESSERA;
DROP TABLE SOCIAL_CLUB;
DROP TABLE CLIENTE;
DROP TABLE DIRETTORE;
DROP TABLE FORNITORE;	
DROP TABLE PERSONA;
DROP SEQUENCE NUOVI_COD_FORN;
DROP SEQUENCE NUOVI_NUM_LOTTO;


CREATE SEQUENCE NUOVI_COD_FORN
START WITH 1000
INCREMENT BY 1
NOMAXVALUE;



CREATE SEQUENCE NUOVI_NUM_LOTTO
START WITH 1000
INCREMENT BY 1
NOMAXVALUE;



CREATE TABLE PERSONA(
CF_PERSONA VARCHAR(16) PRIMARY KEY, 
NOME VARCHAR(20) NOT NULL,
COGNOME VARCHAR(20) NOT NULL,
DATA_DI_NASCITA DATE NOT NULL,
VIA VARCHAR(20) NOT NULL,
CAP VARCHAR(6) NOT NULL,
CITTA CHAR(20) NOT NULL,
SESSO CHAR(1) NOT NULL,
TELEFONO NUMBER,
CONSTRAINTS CHECK_SESSO CHECK(SESSO IN ('M','F','N')));



CREATE TABLE FORNITORE(
CF_FORNITORE VARCHAR(16) PRIMARY KEY,
P_IVA VARCHAR(15) NOT NULL UNIQUE,
CONSTRAINT FK_PERSONA FOREIGN KEY (CF_FORNITORE) REFERENCES PERSONA(CF_PERSONA)ON DELETE CASCADE);


CREATE TABLE DIRETTORE(
CF_DIRETTORE VARCHAR(16) PRIMARY KEY NOT NULL,
TITOLO_STUDIO VARCHAR(30) NOT NULL,
STIPENDIO NUMBER NOT NULL,
DATA_ASSUNZIONE DATE NOT NULL,
CONSTRAINT FK_PERSONA_2 FOREIGN KEY (CF_DIRETTORE) REFERENCES PERSONA(CF_PERSONA)ON DELETE CASCADE);



CREATE TABLE CLIENTE(
CF_CLIENTE VARCHAR(16) PRIMARY KEY NOT NULL,
EMAIL VARCHAR(50) NOT NULL UNIQUE,
CONSTRAINT FK_PERSONA_3 FOREIGN KEY (CF_CLIENTE) REFERENCES PERSONA(CF_PERSONA)ON DELETE CASCADE);



CREATE TABLE SOCIAL_CLUB(
LOCALITA CHAR(50) PRIMARY KEY NOT NULL,
EMAIL_S VARCHAR(50) NOT NULL UNIQUE,
PROPRIETARIO CHAR(50) NOT NULL,
NOME_SOCIAL_CLUB VARCHAR(50) NOT NULL,
NUM_TEL NUMBER NOT NULL,
CF_DIRETTORE VARCHAR(16),
CONSTRAINT FK_DIRIGE FOREIGN KEY (CF_DIRETTORE) REFERENCES DIRETTORE(CF_DIRETTORE) ON DELETE CASCADE);



CREATE TABLE TESSERA(
NUM_TESSERA VARCHAR(20) PRIMARY KEY NOT NULL,
DATA_INIZIO DATE NOT NULL,
DATA_FINE DATE NOT NULL,
COSTO NUMBER NOT NULL,
CF_CLIENTE VARCHAR(16),
LOCALITA CHAR(50),
CONSTRAINT FK_UTILIZZA FOREIGN KEY (LOCALITA) REFERENCES SOCIAL_CLUB(LOCALITA)ON DELETE CASCADE,
CONSTRAINT FK_CLIENTE FOREIGN KEY (CF_CLIENTE) REFERENCES CLIENTE(CF_CLIENTE)ON DELETE CASCADE);



CREATE TABLE SCONTRINO(
NUM_SCONTRINO VARCHAR(20) PRIMARY KEY NOT NULL,
NUM_TESSERA VARCHAR(20) NOT NULL,	
DATA_ORA DATE NOT NULL,
METODO_PAGAMENTRO VARCHAR(20) NOT NULL CHECK(METODO_PAGAMENTRO IN('CONTANTI','CARTA')),
LOCALITA CHAR (50),
CONSTRAINT FK_RICEVE FOREIGN KEY (NUM_TESSERA) REFERENCES TESSERA(NUM_TESSERA)ON DELETE CASCADE,
CONSTRAINT FK_EMESSO FOREIGN KEY (LOCALITA) REFERENCES SOCIAL_CLUB(LOCALITA)ON DELETE CASCADE);



CREATE TABLE TIPO_PRODOTTO(
SOTTOSOTTOTIPO VARCHAR(20) PRIMARY KEY NOT NULL,
SOTTOTIPO VARCHAR (20) NOT NULL,
TIPO_PROD VARCHAR(20) NOT NULL);



CREATE TABLE PRODOTTO(
COD_BARRE VARCHAR(20) PRIMARY KEY NOT NULL,
NOME_PRODOTTO VARCHAR(50) NOT NULL,
PREZZO_VENDITA NUMBER (10,5) NOT NULL,
PREZZO_LISTINO NUMBER (10,5) NOT NULL,
SOTTOSOTTOTIPO VARCHAR(20),
CONSTRAINT FK_CORRISPONDE FOREIGN KEY (SOTTOSOTTOTIPO) REFERENCES TIPO_PRODOTTO(SOTTOSOTTOTIPO)ON DELETE CASCADE);



CREATE TABLE CONTIENE(
QUANTITA_C NUMBER,
NUM_SCONTRINO VARCHAR(20),
COD_BARRE VARCHAR(20),
CONSTRAINT PK_CONTIENE PRIMARY KEY (NUM_SCONTRINO,COD_BARRE),
CONSTRAINT FK_CONTIENE_1 FOREIGN KEY (NUM_SCONTRINO) REFERENCES SCONTRINO(NUM_SCONTRINO)ON DELETE CASCADE,
CONSTRAINT FK_CONTIENE_2 FOREIGN KEY (COD_BARRE) REFERENCES PRODOTTO(COD_BARRE)ON DELETE CASCADE);



CREATE TABLE MAGAZZINO(
NUM_MAG NUMBER PRIMARY KEY NOT NULL,
VIA_M VARCHAR(20) NOT NULL,
CAP_M NUMBER NOT NULL,
LOCALITA CHAR(50),
CONSTRAINT FK_POSSIEDE FOREIGN KEY (LOCALITA) REFERENCES SOCIAL_CLUB(LOCALITA) ON DELETE CASCADE);



CREATE TABLE FORNITURA(
COD_FORNITURA NUMBER PRIMARY KEY NOT NULL,
DATA_FOR DATE NOT NULL,
NUM_MAG NUMBER,
CF_DIRETTORE VARCHAR(16),
CF_FORNITORE VARCHAR(16),
CONSTRAINT FK_ORDINA FOREIGN KEY(CF_DIRETTORE) REFERENCES DIRETTORE(CF_DIRETTORE) ON DELETE CASCADE,
CONSTRAINT FK_CONSEGNATA FOREIGN KEY(NUM_MAG) REFERENCES MAGAZZINO(NUM_MAG) ON DELETE CASCADE,
CONSTRAINT FK_FORNISCE FOREIGN KEY (CF_FORNITORE) REFERENCES FORNITORE(CF_FORNITORE) ON DELETE CASCADE);



CREATE TABLE LOTTO(
NUM_LOTTO NUMBER PRIMARY KEY NOT NULL,
QUANTITA_LOTTO NUMBER (10,5)NOT NULL,
PREZZO_LOTTO NUMBER (10,5) NOT NULL,
COD_BARRE VARCHAR(15),
COD_FORNITURA NUMBER,
CONSTRAINT FK_APPARTIENE FOREIGN KEY(COD_BARRE) REFERENCES PRODOTTO(COD_BARRE)ON DELETE CASCADE,
CONSTRAINT FK_COSTITUITO FOREIGN KEY (COD_FORNITURA) REFERENCES FORNITURA(COD_FORNITURA)ON DELETE CASCADE);



CREATE TABLE APPROVVIGIONAMENTO(
CF_DIRETTORE VARCHAR(16),
DATA_APPROVVIGIONAMENTO DATE NOT NULL,
CONSTRAINT FK_RICHIEDE FOREIGN KEY (CF_DIRETTORE) REFERENCES DIRETTORE(CF_DIRETTORE) ON DELETE CASCADE,
CONSTRAINT PK_APPROVVIGIONAMENTO PRIMARY KEY (CF_DIRETTORE,DATA_APPROVVIGIONAMENTO));



CREATE TABLE COSTITUITO_L(
NUM_LOTTO NUMBER,
DATA_APPROVVIGIONAMENTO DATE,					
CF_DIRETTORE VARCHAR(16),
QUANTITA NUMBER,
CONSTRAINT PK_COSTITUITO_L PRIMARY KEY(NUM_LOTTO,DATA_APPROVVIGIONAMENTO,CF_DIRETTORE),
CONSTRAINT FK_COSTITUITO_L_1 FOREIGN KEY (NUM_LOTTO) REFERENCES LOTTO(NUM_LOTTO) ON DELETE CASCADE,
CONSTRAINT FK_COSTITUITO_L_2 FOREIGN KEY (CF_DIRETTORE,DATA_APPROVVIGIONAMENTO) REFERENCES APPROVVIGIONAMENTO (CF_DIRETTORE,DATA_APPROVVIGIONAMENTO) ON DELETE CASCADE);


CREATE TABLE REPARTO(
TEL_REP NUMBER NOT NULL,
TIPO_REPARTO CHAR(20) NOT NULL,
NUM_MAG NUMBER NOT NULL,
CONSTRAINT PK_REPARTO PRIMARY KEY (NUM_MAG,TIPO_REPARTO),
CONSTRAINT FK_SUDDIVISO FOREIGN KEY (NUM_MAG) REFERENCES MAGAZZINO(NUM_MAG) ON DELETE CASCADE);


CREATE TABLE CONTIENE_R(
TIPO_REPARTO CHAR(20),
SOTTOSOTTOTIPO VARCHAR(20),
NUM_MAG NUMBER,
CONSTRAINT PK_CONTIENE_R PRIMARY KEY (TIPO_REPARTO,SOTTOSOTTOTIPO,NUM_MAG),
CONSTRAINT FK_CONTIENE_R_1 FOREIGN KEY (NUM_MAG,TIPO_REPARTO) REFERENCES REPARTO(NUM_MAG,TIPO_REPARTO) ON DELETE CASCADE,
CONSTRAINT FK_CONTIENE_R_2 FOREIGN KEY (SOTTOSOTTOTIPO) REFERENCES TIPO_PRODOTTO(SOTTOSOTTOTIPO) ON DELETE CASCADE);



CREATE TABLE VENDUTO(
COD_BARRE VARCHAR(20),
PREZZO_FORNITORE NUMBER (10,5) NOT NULL,
CF_FORNITORE VARCHAR(16),
CONSTRAINT PK_VENDUTO PRIMARY KEY (CF_FORNITORE,COD_BARRE),
CONSTRAINT FK_VENDUTO_1 FOREIGN KEY (COD_BARRE) REFERENCES PRODOTTO(COD_BARRE) ON DELETE CASCADE,
CONSTRAINT FK_VENDUTO_2 FOREIGN KEY (CF_FORNITORE) REFERENCES FORNITORE(CF_FORNITORE) ON DELETE CASCADE);

